version: '3.8'
services:
  openwrtsimet:
    container_name: openwrtsimet
    volumes:
      - "./:/app"
    env_file:
      - ./docker/.env_openwrt
    build:
      context: .
      dockerfile: ./docker/Dockerfile