version: '3.8'
services:
  openwrtsimet:
    container_name: openwrtsimet
    volumes:
      - "./inventory/:/ansible/inventory/"
      - "./playbooks/:/ansible/playbooks/"
      - "./config/hosts:/etc/hosts"
      - "./libs/:/ansible/"
      - "./env/namespaces.py:/usr/local/lib/python3.10/dist-packages/pycw7-0.0.11-py3.10.egg/pycw7/utils/xml/namespaces.py"
      - "./env/namespaces.py:/ansible/pycw7/utils/xml/namespaces.py"
    env_file:
      - ./docker/.env_openwrt
    build:
      context: .
      dockerfile: ./docker/Dockerfile